### ISSUE TITLE
Update NuGet Icon

### ISSUE THREAD

**Issue by jamesmontemagno** [cjlotz/Xamarin.Plugins#10]
If you want I created a few new templates for the icons that you can add to if you want.

Icon 1:
https://raw.githubusercontent.com/jamesmontemagno/Xamarin-Templates/master/Plugins-Templates/icons/plugin_icon.png

**Comment by cjlotz** [comment]
I'm currently away on leave till end of next week. I'll have a look at it when I have access to a computer again.
