### ISSUE TITLE
Unable to perform call on iOS

### ISSUE THREAD

**Issue by TorbenK** [cjlotz/Xamarin.Plugins#12]
Hi,

I'm unable to perform a call on iOS. I always get an exception sayin the NSString couldnt be parsed.

I also tried removed whitespaces and signs like "+" from the number but nothing worked.

Any ideas?

**Comment by cjlotz** [comment]
Smmm, strange.  Here's the snippet from the sample project PCL to make a phone call.

```csharp
public static void MakeSamplePhoneCall(this IPhoneCallTask phoneCall)
{
    if (phoneCall.CanMakePhoneCall)
    {
        phoneCall.MakePhoneCall("+272193343499", "Xamarin Demo User");
    }
}
```

**Comment by cjlotz** [comment]
Pending further feedback this issue is now closed
