### ISSUE TITLE
Add attachments on WP8.1

### ISSUE THREAD

**Issue by noberasco** [cjlotz/Xamarin.Plugins#13]
Hi,

first of all, thanks for your efforts on this project.

Since WP8.1 does support email with attachments (via EmailMessage and EmailManager), I wonder if you can update the library and add support for attachments on WinPhone.

Regards,
Michele Noberasco

**Comment by cjlotz** [comment]
Not sure I understand the issue as the plugin provides support for WP 8.1 attachments.  Have a look at the WinPhoneRT sample.

**Comment by noberasco** [comment]
Hi,

I did have a look at the WinPhoneRT sample, effectively the implementation is the one I'm looking for. However, I find myself unable to use it.

Context: I'm linking your library from a Xamarin Forms project (iOS, WP8.1 and Android). For some reason, when I fetch your library from NuGet, the WP8.1 project gets linked to the WinPhone variant of your library (where attachments are not available) instead of the WinPhoneRT variant. Do you have any idea why this happens, and what can I do to fix it?

Regards,
Michele
