### ISSUE TITLE
Messaging does not work if there's a BackgroundAgent

### ISSUE THREAD

**Issue by fonix232** [cjlotz/Xamarin.Plugins#15]
I've been having this issue since I started using Xam.Plugins.Messaging:
- If I add the plugin reference only to my main WP project, it does not work, it dies with a NotImplementedException
- If I add the reference to the BackgroundAgent too, it works, but then the Windows Store won't accept the XAP, saying the BackgroundAgent uses restricted APIs (mobility cannot be used in a background service).

What would be a simple solution in this case?

**Comment by cjlotz** [comment]
@fonix232 What version of Windows Phone are you using?  W.r.t the BackgroundAgent - the Sms, Phone and Email functionality uses the default platform UI for sending a Sms, Email or making a Phone call.  These API's aren't allowed in Background agents.

**Comment by fonix232** [comment]
It's WP8 base (our client requires backwards compatibility for now...). I'm very well aware of the BackgroundAgent limitations, and that's why I don't understand how it is possible that the Messaging plugin won't work when it is not added to it.

**Comment by jamesmontemagno** [comment]
You most likely just need to manually reference the assemblies that are added to the PCL project. So instead of adding the NuGet to the background agent solution go and just manually reference the files from the packages/lib/pcl-net45+.... folder.

That would make it work fine.
