### ISSUE TITLE
Adding Multiple SMS Recipients

### ISSUE THREAD

**Issue by rlingineni** [cjlotz/Xamarin.Plugins#28]
Is it possible to add more than 1 recipient in an SMS message?

**Comment by Seen6** [comment]
I am interested in any solution for IOS multiple recipient... Put send method in a loop doesn't work

**Comment by cjlotz** [comment]
@rlingineni Seems like this can be achieved however on Android there [seems to be an issue with Samsung devices](http://stackoverflow.com/questions/18974898/send-sms-through-intent-to-multiple-phone-numbers/18975676#18975676) which require different separator.  Building this kind of device/manufacturer behaviour into the plugin is not necessarily something I'm keen on doing.  I'll consider some design options for this.

@Seen6  Will look at adding this in next update

**Comment by cjlotz** [comment]
Implemented in the latest v4 version of the plugin
