### ISSUE TITLE
Android - Using MessagingPlugin.SmsMessenger.SendSms pass the message to default app instead of sending

### ISSUE THREAD

**Issue by nolazybits** [cjlotz/Xamarin.Plugins#33]
If I use MessagingPlugin.SmsMessenger.SendSms the message is pass to the default app (hangout for instance) and never sent (using the intent, it is up to the default app to react to it)

Using SmsManager does send the message directly, but needs permission to do so (SEND_SMS).
Would it be possible to flag what method we would like to use on android platform?

Thanks.

**Comment by cjlotz** [comment]
If I understand your correctly, you want the ability on the plugin to use either the Intent or SmsManager for sending the SMS?

**Comment by cjlotz** [comment]
No further feedback
