### ISSUE TITLE
Opens app select instead of going directly to default mail app on Android?

### ISSUE THREAD

**Issue by eddnav** [cjlotz/Xamarin.Plugins#34]
Using this simple convenience method:

``` C#
Device.OpenUri(new Uri("mailto:contact@contact.com"));
```

The default email app is launched as expected.

Using the plugin:

``` C#
var emailMessenger = CrossMessaging.Current.EmailMessenger;
if (emailMessenger.CanSendEmail)
{
     emailMessenger.SendEmail("mailto:contact@contact.com", "", "');
}
```

Seems to launch a more general text share intent (it's using the simple API there, but even when using the builder and filling all cc, bcc, etc fields, it still doesn't launch the default app).

Is there something I'm missing?

**Comment by cjlotz** [comment]
The plugin follows the [guidance provided by Xamarin](http://developer.xamarin.com/recipes/android/networking/email/send_an_email/) on how to send an email using an Intent.   The guidance states that by setting the `Intent` mime type using `email.SetType ("message/rfc822")` will cause applications capable of handling email to launch.  If you have multiple apps capable of doing this, you will get a list of apps to choose from.

From reading the [guidance provided by Google](http://developer.android.com/guide/components/intents-common.html#Email) they state that using the more specific `ACTION_SENDTO` intent and the `mailto` uri scheme will ensure that only email apps handle the action.  This seems to be the behaviour your are getting by using your convenience method.

Do you get a different list of apps when using the plugin vs your convenience method, or does the plugin show a list of apps to choose from, whilst your convenience method launches the email application directly?  If the plugin shows a list of applications capable of handling the intent, does this not include the default email application?

**Comment by Matti-Koopa** [comment]
I'm not OP, but I can confirm this behavior. The default e-mail client DOES show up in the list, but so do other apps clearly not capable of sending e-mails.
Most prominently, these include: What's App, Microsoft OneNote, Microsoft OneDrive, Google Cloud

We actually got user feedback that this list is confusing. We use this plugin for a "Feedback" option and intend the user to write an e-mail to us, which pre-includes some technical data in the body. The users might actually expect that they can use What's App to send their feedback to us, while we do not even have a What's App account.

On top of that, on iOS and Windows the default e-mail app launches without this list. I would expect a similar behavior on Android.

I'd love for this plugin to filter only "true" e-mail apps or just show the default e-mail app. Maybe make this an optional parameter if you choose to do so.
Thank you.

**Comment by cjlotz** [comment]
I've added a new `UseStrictMode` to the`EmailMessageBuilder` that uses the Google recommended practice to limit the list to only email apps.  This works fine from my testing but unfortunately sending attachments using the Strict Mode doesn't seem to work from my testing.  Seems I'm not [the only one]( http://stackoverflow.com/questions/15946297/sending-email-with-attachment-using-sendto-on-some-devices-doesnt-work) running into these issues.

StrictMode will be available as part of the v4 release.
