### ISSUE TITLE
How to detect when user tap "Send" button on email?

### ISSUE THREAD

**Issue by deadean** [cjlotz/Xamarin.Plugins#35]
I need a post action for SendEmail method. Can I do this?

**Comment by cjlotz** [comment]
Not sure I understand your question.  Please have a look at the sample projects for illustrated usages.

**Comment by deadean** [comment]
I will be thankful if I could invoke some code after user tap "send" button when sending an email.

**Comment by cjlotz** [comment]
@deadean This is unfortunately not within the scope of the plugin.  The plugin's responsibility ends when it launches the default applications that take care of the sending the email/sms/making phone call.
