### ISSUE TITLE
CanSendEmail always comes false

### ISSUE THREAD

**Issue by ShahriatHossain** [cjlotz/Xamarin.Plugins#38]
I am trying to use some of your code to send email from my shared project instead of platform specific. Not sure which code I need to use to send from shared project PCL in Xamarin.Forms. Can you help me?

**Comment by Vinnie1991** [comment]
Did you use it on the simulator or on a real device?

Apple (I don't know about Android, only using Apple now) doesn't support sending an email (or call/text) from the simulator. You need to test/develop it on a real device with an email account configured on it.

Let me know if you need anymore help

**Comment by cjlotz** [comment]
No further feedback
