### ISSUE TITLE
CanSendEmail doesn't seem to work on iOS 10 if the mail app has been removed.

### ISSUE THREAD

**Issue by matthewjclay** [cjlotz/Xamarin.Plugins#41]
I use outlook for my mail account.  Seems the check is not for accounts, or does not open the default client?  The same check then works if the mail app is restored.

**Comment by cjlotz** [comment]
The plugin uses the `MFMailComposeViewController` on iOS to send e-mail ([read more here](https://developer.apple.com/reference/messageui/mfmailcomposeviewcontroller)).  An alternative is to use the `mailto` URL protocol which should open Outlook in your scenario, however, the protocol is less feature rich in that it does not cater for attachments.  I'm therefore not planning to support this in the plugin as I prefer the feature rich API for the majority use case on iOS.

**Comment by matthewjclay** [comment]
Makes sense. Thanks for taking the time to reply. I may switch to the URL scheme.
