### ISSUE TITLE
Can only send mail using Apple Mail on iOS

### ISSUE THREAD

**Issue by fela98** [cjlotz/Xamarin.Plugins#43]
If the user hasn't set up his mail account with apple mail. CanSendMail is set to false. It would be great however to also try to send mail using Outlook or Google Mail. They have their own URL schemes:

gmail:
https://www.macstories.net/links/gmail-for-ios-url-scheme/
outlook:
http://stackoverflow.com/questions/32369198/i-just-want-to-open-ms-outlook-app-and-see-mailto-screen-using-url-scheme-at-ios

**Comment by cjlotz** [comment]
Closing this as trying to build in support for different url schemes into the plugin doesn't make sense.   Seems like the supported flow is to setup the Mail app to use your GMail/Outlook account.
