### ISSUE TITLE
How to send email anonymously in backgroud ?

### ISSUE THREAD

**Issue by ericbrunner** [cjlotz/Xamarin.Plugins#46]
Hi, 

I want to send emails in the background without user interaction, even to track if someone wants to authenticate which is not authorized. I already send such information to my Application Insights config in Azure. So I get the info anyway. But for convenience it would be great if I can specifiy a **To:** (sender) like noreply@myapp.com . Currently when the app attempts to send an email the standard android email program choose dialog pops up where a user would have to choose its own email account, which is not the desired behaviour.

thanks,
Eric

**Comment by cjlotz** [comment]
Sending an email in the background falls outside of the scope of the plugin.  The plugin specifically only uses what is already setup on the device in terms of email.  It does not try to configure any email account settings etc. to send under a different identity.
