### ISSUE TITLE
not able to attach file

### ISSUE THREAD

**Issue by iamchandresh** [cjlotz/Xamarin.Plugins#49]
please review my code as I am not able to attach any file in EmailMessageBuilder, Also I need to understand about the ContentType, what should I pass in ContentType?

FileData filedata = await CrossFilePicker.Current.PickFile();
String Path = CrossGetLocalFilePath.Current.GetLocalPath(filedata.FileName);
var emailMessenger = CrossMessaging.Current.EmailMessenger;
if (emailMessenger.CanSendEmail)
{
  var email = new EmailMessageBuilder()
  .To("to.plugins@xamarin.com")
  .Subject("Xamarin Messaging Plugin")
  .Body("Well hello there from Xam.Messaging.Plugin")
  .WithAttachment(Path, "image/jpeg")
  .Build();
  emailMessenger.SendEmail(email);
}

**Comment by chandresh07** [comment]
I am using above code in Xamarin.forms (Portable).
my attachment could be image, video or any file.

**Comment by glennstephens** [comment]
Its a result of Android M changes and the attachments need to use the FileProvider class for sending them. XLabs has done this already at https://github.com/XLabs/Xamarin-Forms-Labs/pull/1120/commits/424a86849255ed6f59a774be399b3f77f6723c6e, so its a matter of the plug-in being changed

**Comment by iamchandresh** [comment]
I am getting issue in Android 5.1.0
