### ISSUE TITLE
'CanMakePhoneCall' is returning true for Nexus 7/10 devices 

### ISSUE THREAD

**Issue by mohan636143** [cjlotz/Xamarin.Plugins#51]
Nexus 7/10 Tablet doesn,t support calling .
But still the check returns true

**Comment by Julien-Mialon** [comment]
Got the same issue, seems to be relative to the fact that the check on CanMakePhoneCall is on the Dial intent but without parameter. A check on the intent with a Uri "tel:0000000000" (with a fake number) seems to work.
