### ISSUE TITLE
Documentation of usage

### ISSUE THREAD

**Issue by candidodmv** [cjlotz/Xamarin.Plugins#53]
Hello, before of all, congrats for sharing this amazing plugin. But, I'm having difficult to find the documentation, like how to install, how to setup, anything that help me to get started.  Thanks so much!

**Comment by cjlotz** [comment]
Start by reading the docs [here](https://github.com/cjlotz/Xamarin.Plugins/blob/master/Messaging/Details.md) and by looking at the code provided in the Plugin.Messaging.Samples.sln

**Comment by candidodmv** [comment]
thank you!
