### ISSUE TITLE
Android Email Attachments - File Provider "content://" paths not supported

### ISSUE THREAD

**Issue by dylanberry** [cjlotz/Xamarin.Plugins#54]
Hi @cjlotz,

I was moving to the Android Nougat style FileProvider to handle my app's attachments and found that on [line 74 of Messaging/Plugin.Messaging.Android/EmailTask.cs](https://github.com/cjlotz/Xamarin.Plugins/blob/5a819be6849413e7b30418e86e671961adf38f91/Messaging/Plugin.Messaging.Android/EmailTask.cs#L74), the attachment logic always adds in "file://".

`var uri = Android.Net.Uri.Parse("file://" + attachment.FilePath);`

This causes parsing to fail for the FileProvider "content://" style urls.

Would you accept a pull request to fix this? I was planning to replace this with the following:

`var uri = Android.Net.Uri.Parse(attachment.FilePath.Contains("content://") ? attachment.FilePath : "file://" + attachment.FilePath);`

Thanks!
Dylan

**Comment by dylanberry** [comment]
Taking a look at your development branch, I see you have made some fixes for this already...

**Comment by cjlotz** [comment]
@dylanberry The plan is to release an alpha version with support for using the FileProvider on Nougat.  The alpha release will drop support for some older platforms like Windows Phone but also hopefully include some minor enhancements/improvements on the API.  I still need to plan around what enhancements to include, but I'm thinking to get out an alpha that only includes the FileProvider support as this is the immediate need.

**Comment by cjlotz** [comment]
`FileProvider` support has been added in the latest release of the plugin.
