### ISSUE TITLE
Attachement in IOS

### ISSUE THREAD

**Issue by sansantosh** [cjlotz/Xamarin.Plugins#55]
I am getting this exception on IOS :  No overload for method `WithAttachment' takes `1' arguments (CS1501)

**Comment by cjlotz** [comment]
The `WithAttachment` Api has been reworked in the latest version of the plugin as it was causing confusion amongst users.   The platform versions of the `WithAttachment` now takes a platform specific files as attachments (`NSUrl` on iOS).
