### ISSUE TITLE
Change Dial to Call on Android?

### ISSUE THREAD

**Issue by Osmosis311** [cjlotz/Xamarin.Plugins#58]
On Android, the dial action only puts the number into the dialer, it doesn't automatically dial.

Over here:
https://github.com/cjlotz/Xamarin.Plugins/blob/master/Messaging/Plugin.Messaging.Android/PhoneCallTask.cs#L37

...as I understand it, if ACTION_CALL is used instead, it will do this.

Thanks!

**Comment by cjlotz** [comment]
From the [Google docs](https://developer.android.com/guide/components/intents-common.html#Phone), using the `ACTION_CALL` would require the user to add the  `CALL_PHONE` permission to their manifest file.  This will be  a breaking change for existing users of the plugin that now needs to include the additional permission for their apps.
