### ISSUE TITLE
iOS SMS, Email - Broken in Xamarin.Forms 2.3.4

### ISSUE THREAD

**Issue by eopeter** [cjlotz/Xamarin.Plugins#59]
With the latest Xamarin Forms release 2.3.4.214, on SMS, only keyboard shows. Nothing happens on Email. Phone works fine. This is for the iOS version in both device and simulator.

**Comment by cjlotz** [comment]
@eopeter I've added a forms sample to simulate your errors, but I'm not seeing the same issues. It works fine on the device. Please note that you cannot test the plugin functionality on the simulator as you cannot test phone, sms and email on the simulator itself.

**Comment by mnidhk** [comment]
I have the same problem!
I have a test project in Xamarin forms and updated to 4.0 version of the message plugin.
Xamarin forms was on 2.3.3.168. Everything is working fine.
When i update my Xamarin Forms project to Xamarin forms 2.3.4.231 ( and the same Xamarin.forms.maps) the email function does stop working. No email screen is popping up.
Making a call is still working
Going back to previous package of message plugin doesn't matter so it looks like it has to do with Xamarin.forms 2.3.4.231

**Comment by alanspires** [comment]
+1 email no longer works in 2.3.4.247.

**Comment by alanspires** [comment]
this should be reopened

**Comment by alanspires** [comment]
This is fixed in Xam Forms 2.3.5 betas. I believe this had to do with calling it from an actionsheet.
