### ISSUE TITLE
AutoDial in IOS and UWP

### ISSUE THREAD

**Issue by danipazos** [cjlotz/Xamarin.Plugins#62]
Hello,

Can you use the AutoDial property in IOS and UWP projects?

In the messaging plugin there's only a reference to Android. 

Thank you

**Comment by cjlotz** [comment]
To the best of my knowledge this is not supported on iOS [refer to this link] (https://stackoverflow.com/questions/43121740/prompt-when-trying-to-dial-a-phone-number-using-tel-scheme-on-ios-10-3) and UWP so we cannot provide similar functionality on these platforms.
