### ISSUE TITLE
HTML Formatting does not seem to work on Android

### ISSUE THREAD

**Issue by cjlotz** [cjlotz/Xamarin.Plugins#64]

**Comment by cjlotz** [comment]
I've done some further testing on this and the functionality seems to be working like it should.  Seems like it depends on the email client though.  When sending using GMail app on my phone I don't see the HTML formatting, but sending with another email client like AquaMail I do see the formatting

**Comment by appsandbeyond** [comment]
Sorry for my limited knowledge on Android. This was really a pain to get working. After all we didn't do anything wrong. Lots of thanks for your fast response!
