### ISSUE TITLE
How to know if the mail was sent successfully?

### ISSUE THREAD

**Issue by sskohli** [cjlotz/Xamarin.Plugins#65]
Hi,
Thanks for a great plugin.
Is there a way to tell if the mail was sent successfully in iOS?
In Android a separate email client is opened, so we can't do much.
But in iOS there's a status if the mail was sent or not.
Can we track it using this plugin?

Thanks,
Sandeep

**Comment by cjlotz** [comment]
From the [iOS documentation](https://developer.apple.com/documentation/messageui/mfmailcomposeviewcontroller):

> Although the view controller reports the success or failure of the operation to its delegate, this class does not provide a way for you to verify whether the email was actually sent.

So unfortunately there is no way to support this.
