### ISSUE TITLE
Doesn't Work on First Launch of App

### ISSUE THREAD

**Issue by kartiksolanki** [cjlotz/Xamarin.Plugins#69]
Hi, I have used this plugin in my Xamarin.Forms project and I have found one issue. This plugin doesn't work on the first launch of my app downloaded from the store but when I restart the app, the functionality works like a charm. Any idea what can be the reason?

**Comment by kartiksolanki** [comment]
The debug log says - "Warning: Attempt to present <MFMessageComposeViewController: 0x103733200> on <Xamarin_Forms_Platform_iOS_ModalWrapper: 0x10b33ebe0> whose view is not in the window hierarchy!"

**Comment by cjlotz** [comment]
Duplicate of #72
