### ISSUE TITLE
Is the plugin compatibile with .Net Standard ?

### ISSUE THREAD

**Issue by gptucci** [cjlotz/Xamarin.Plugins#70]
Tanks for this beautiful package !
When I try to install in Xamarin.Forms targeting .Net Framework 1.4 I get:
Xam.Plugins.Messaging 4.0.0 is not compatible with netstandard1.4

Xam.Plugins.Messaging will be compatible with next releases with .Net Framework ?
Tnx

**Comment by cjlotz** [comment]
I'm busy adding support for .NET Standard on the develop branch.  Hope to have a beta version out sometime this week.

**Comment by cjlotz** [comment]
I've just published a beta version with .NET Standard support to NuGet.
