### ISSUE TITLE
(UWP) Attachment not added when using outlook as the default email application

### ISSUE THREAD

**Issue by JorisZwaenepoel** [cjlotz/Xamarin.Plugins#73]
I am using this component to send an email with attachment from a Xamarin Forms app, but when my app is run on Windows 10 and Outlook is the default email app, the attachment is not added to the email.  
When using the "Mail" app that comes with Windows 10, it works as expected (the attachment is included).

Is this a known issue?
Is there a workaround for this problem?

**Comment by cjlotz** [comment]
@JorisZwaenepoel Unfortunately I don't have a setup to verify this.  I ran the UWP sample (not UWP forms though) on the latest v5 release on a Windows Phone that uses the Outlook Email client and the attachment functionality was working.  

Perhaps try with the latest version of the plugin released?  I also updated the samples to now directly reference the source code of the plugin so it should be a lot easier to try and debug this kind of issue using the sample projects.

**Comment by prashantvc** [comment]
@JorisZwaenepoel @cjlotz I verify this issue on an UWP app too (on Windows Fall update) and not able to reproduce.

A sample demonstrating the issue will really help to troubleshoot it.

**Comment by JorisZwaenepoel** [comment]
Hi @prashantvc, @cjlotz,

I attached a sample project that demonstrates the issue.
I also attached 2 screenshots:  1 from the Windows Mail-app (where everything works as expected: the attachment is there), and 1 when Outlook is the default email app (and here, as you can see, the attachment is missing).  

Thanks in advance for having a look at this.
Kind regards,
Joris

![screenshot outlook](https://user-images.githubusercontent.com/16609982/33073417-294aa5de-cec3-11e7-9a5d-8ee5fc824b01.png)
![screenshot windows mail](https://user-images.githubusercontent.com/16609982/33073418-2962fdb4-cec3-11e7-9025-c0edc84a1185.png)
[XFEmailSample.zip](https://github.com/cjlotz/Xamarin.Plugins/files/1491352/XFEmailSample.zip)

**Comment by prashantvc** [comment]
@JorisZwaenepoel this is know issue with UWP platform. The attachment works only with the other UWP apps.

This issue is being discussed there on the [MSDN forums](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/5a539ff6-ce81-4f05-83a0-8bf430d827f8/uwpwindows-10-c-universal-windows-app-email-with-attachment?forum=wpdevelop). Right now it is recommended to create a feature request at http://wpdev.uservoice.com
