### ISSUE TITLE
Phone calls don't work properly in iOS 11

### ISSUE THREAD

**Issue by OpticNectar** [cjlotz/Xamarin.Plugins#74]
When I try to make a call I get this error:

```
-canOpenURL: failed for URL: "tel:0000000000" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
```

I've tried passing in different strings etc and nothing works properly and it seems to think i'm passing in all zeros. I'm using `Xamarin.Forms` version `2.4.0.38779` and testing it on iOS 11.

**Comment by cjlotz** [comment]
A code sample of how you are using the plugin to make a phone call would be helpful.

**Comment by OpticNectar** [comment]
@cjlotz Turns out it was a simulator issue, and it works on the device properly.
