### ISSUE TITLE
Custom navigation iOS

### ISSUE THREAD

**Issue by olegtyshcneko** [cjlotz/Xamarin.Plugins#78]
In our project, we rely on MVVMCross to operate all navigation. We have some tricky cases, where we need to show overlay view above other views which doesn't block any other navigation. So we have additional logic in presenter to resolve some kind of navigation issues while the overlay is shown. Your module does his own stuff, which is working okay in most cases, but in some cases, we need to run some custom code on navigation. Is it possible to add an ability to customize how MFMailcomposeViewContoller is shown? 

For example, add some interface which can be injected (property injection) and by default, you can set implementation that is present(present using root view controller)?

**Comment by cjlotz** [comment]
@olegtyshcneko I've added some functionality as requested in the latest beta.  More details available [here](https://github.com/cjlotz/Xamarin.Plugins/blob/master/Messaging/Details.md#custom-navigation-ios).  Let me know if this works for you.
