### ISSUE TITLE
Email composer view seems to reset the NavigationStack when closed

### ISSUE THREAD

**Issue by LuisDeHaro** [cjlotz/Xamarin.Plugins#80]
Hi guys,

I'm using the plugin in order to compose a pre-filled email both in iOS and Android. Everything works OK, when i use the following code (in my ViewModel) it opens the email composer:

```
CrossMessaging.Current.EmailMessenger.SendEmail(
null, 
StringUtils.UppercaseFirstEach(this.current_discount.discount_name),
string.Format("{0} {1}", lang.social_email_share_body_template, StringUtils.UppercaseFirstEach(this.current_discount.discount_name))
);
```
However, when I close the composer it seems to reset the Navigation Stack and sends me to the main ContentPage in my project.

Here's a video with the issue:
https://drive.google.com/file/d/1E4Zim9CTJZ2uCdEQmcTswMFPhNpaOnCn/view

Any help will be appreciated. Thanks!

**Comment by djooleean** [comment]
iOS:
Same problem with the SMS composer task...
I launch the SMS messenger task from a popup, and when I come back to the app (after sending the SMS), the popup is closed ...
Any clue / workaround ?
Thx
