### ISSUE TITLE
Can't attach file in iOS

### ISSUE THREAD

**Issue by tselvan2311** [cjlotz/Xamarin.Plugins#81]
I tried to attach image file from path "/var/mobile/Containers/Data/Application/CFE323DCB-535A-4120-8532-8F8463E6B39/Documents/awik.png" in iOS. 
But it throws exception called "invalid arguments (argument name: attachment)". 

In detail, In iOSUnified project,  EmailTask.cs file, line no 50,
`_mailController.AddAttachmentData(NSData.FromFile(attachment.FilePath), attachment.ContentType, attachment.FileName);`

NSData always passed as null. 

FYI, I'm using V 4.0.0

**Comment by cjlotz** [comment]
@tselvan2311 Are you getting the same issue when using `v5` of the plugin?  Are you attaching the image from a PCL project or from iOS project?  Have you looked at the `SendAttachmentsEmail` sample code in [iOS sample project](Xamarin.Plugins/Messaging/Plugin.Messaging.iOSUnified.Sample/RootViewController.cs)

**Comment by cjlotz** [comment]
Closing due to lack of further feedback
