### ISSUE TITLE
How to mention path for attachment in Email in PCL?

### ISSUE THREAD

**Issue by kartiksolanki** [cjlotz/Xamarin.Plugins#83]
I am working on a Xamarin.Forms PCL application and how should I mention the path.
For example, my solution has three folders: TestApp, TestApp.Droid and TestApp.iOS. I have a file in TestApp (PCL) where I have used Plugins.Messaging. And I want to attach the PDF file which is located at TestApp (Shared) > Data > Content > 123.pdf.

So how should I mention the local path of the pdf file? Also, what should I specify in ContentType for pdf?
Any help would be greatly appreciated.

**Comment by prashantvc** [comment]
@kartiksolanki The plugin will launch the system default activity or another app's activity. These activities will not have access to the file saved in your app's isolated location.

You will need to move the file to shared storage and use that path to attach it to an email

**Comment by kartiksolanki** [comment]
@prashantvc  I have the file in my shared path only like for example, I have: 
"TestApp (Shared) > Data > Content > 123.pdf." 

How should I mention the path in the above scenario?
