### ISSUE TITLE
Can't build samples

### ISSUE THREAD

**Issue by fgiacomelli** [cjlotz/Xamarin.Plugins#86]
Hello, I just downloaded this plugin to test it on a device discovering that namespaces Media and MediaFiles are not available:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Media' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?)	Plugin.Messaging.iOSUnified.Sample	\Xamarin.Plugins-master\Messaging\Plugin.Messaging.iOSUnified.Sample\RootViewController.cs	5	Active

both in Android and ios projects

**Comment by cjlotz** [comment]
These namespaces are from the the Xamarin.Mobile component referenced from the Xamarin Mobile Component Store.  I know Xamarin is retiring the component store, so this might be the reason for it not restoring as part of the build process.  I've unignored the Components folder that contains my local downloaded copies of the Xamarin.Mobile component.  Hopefully that solves your compile issues.

**Comment by fgiacomelli** [comment]
Thank you for your reply. I was able to build the samples removing the
instructions that failed (related to attachments), but I discovered later
that this plugin can't send emails in background, but it always use the
standard email client from the OS where is running

2018-01-17 19:09 GMT+01:00 Carel Lotz <notifications@github.com>:
