### ISSUE TITLE
Email body is empty in Outlook App on Android

### ISSUE THREAD

**Issue by amalwankar** [cjlotz/Xamarin.Plugins#87]
When using this xam.messaging plugin to send email in Android and choosing Outlook app from the App Chooser menu, the email body is empty, while the subject and to fields get set correctly as expected. Please note that this only happened with Outlook App and the plugin works as expected with Yahoo and Google Inbox apps. This is an issue while using **BodyAsHtml** on EmailMessageBuilder.

**Comment by cjlotz** [comment]
Unfortunately there is no way for the plugin to support app specific behaviour for different e-mail clients.  This seems to be an issue with the Outlook App's support for sending HTML e-mail and not something that the plugin can control.
