### ISSUE TITLE
Sms is not sent on dual sim phones

### ISSUE THREAD

**Issue by harrisd13** [cjlotz/Xamarin.Plugins#89]
Background sms in dual sim Android phones fails to be sent automatically. It's added into sms application and makes the user select which sim to use for sending.

There should be a feature to be able to add the preffered sim automatically or send it with either sim.

**Comment by cjlotz** [comment]
Did some reading on the topic and there does not seem to be a public api available to do this.  There are [some hacky and unreliable solutions](https://stackoverflow.com/questions/27351936/how-to-send-a-sms-using-smsmanager-in-dual-sim-mobile) to do this via reflection but I'm not keen on supporting this if there is not an official API for getting this accomplished.
