### ISSUE TITLE
HTML is being stripped from the message.

### ISSUE THREAD

**Issue by FrazzApps** [cjlotz/Xamarin.Plugins#90]
The <a> tag is being stripped when I send this message:

```
   var msg = "Well hello there from <a>Xam.Messaging.Plugin</a>";
                var email = new EmailMessageBuilder()
                  .To("")
                  .Subject(AppResources.Email_Share_Subject)
                  .BodyAsHtml(msg)
                  .Build();
                
                var emailTask = Plugin.Messaging.CrossMessaging.Current.EmailMessenger;

                emailTask.SendEmail(email);
```

**Comment by cjlotz** [comment]
@FrazzApps On what platform is this happening?  Please provide some more context.

**Comment by FrazzApps** [comment]
Sorry It's on Android 7.0
and I'm on Xamarin Forms 2.5.0.122203
and I have Xam.Plugin.Messaging 5.1.0 installed

**Comment by FrazzApps** [comment]
(clicked the wrong button)

**Comment by cjlotz** [comment]
@FrazzApps What e-mail app are you using to send the e-mail?  Gmail?

**Comment by FrazzApps** [comment]
Yes Gmail

**Comment by cjlotz** [comment]
@FrazzApps I've had problems with the HTML support in the GMail app.  It doesn't seem to work which is unfortunate as this is by far the most used app for sending e-mail on Android.  When I run the HTML sample on my own device, the email is formatted correctly when sending it using another email client like Aquamail.  However, when using Gmail, the HTML content is not formatted correctly. Other users are reporting the (same issue)[https://stackoverflow.com/questions/42382912/has-androids-gmail-app-removed-the-ability-to-send-html-emails-via-intent]

**Comment by FrazzApps** [comment]
That's really too bad since the <a> tag would seem to be critical for most applications...
