### ISSUE TITLE
Remote service does not respond to _accessibilityMachPort

### ISSUE THREAD

**Issue by gabrielrobert** [cjlotz/Xamarin.Plugins#91]
Hi,

Is this something we can address from your plugin?
I would be happy to send a pull request if you have any idea on `how to fix it`.

Many thanks.

## Bug Information

Version Number of Plugin: **5.1.0**

Device Tested On: **iPad Pro 12**

Version of VS: **VS Mac 7.3.3 (build 17)**

Version of Xamarin: **Xamarin.Forms -> 2.5.0.121934**

Versions of other things you are using:
```
BTProgressHUD -> 1.2.0.6
LiveXAML -> 2.1.16
Microsoft.AppCenter.Analytics -> 1.3.0
Microsoft.AppCenter.Crashes -> 1.3.0
Plugins.Forms.ButtonCircle -> 1.3.9
Refit -> 4.1.0
SQLiteNetExtensions -> 2.0.0
SQLiteNetExtensions.Async -> 2.0.0
Xam.Plugins.Messaging -> 5.1.0
Xamarin.Forms -> 2.5.0.121934
Xamarin.TestCloud.Agent -> 0.21.3
SegmentedControl.FormsPlugin -> 1.3.4
```

### Steps to reproduce the Behavior

1. Install the latest version of plugin
2. Copy-paste code snippet
3. Run application and try to send email

### Expected Behavior
`Mail` application open successfully without noises.

### Actual Behavior

`Mail` application open with the error `AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}` in console every 0.2 seconds.

### Code snippet

**AppDelegate**:

```
#if ENABLE_TEST_CLOUD
            Calabash.Start();
#endif
```

**Actual sender**:
```
var builder = new EmailMessageBuilder()
    .To(to)
    .Cc(cc)
    .Bcc(bcc)
    .Subject(subject)
    .Body(body);

CrossMessaging.Current.EmailMessenger.SendEmail(builder.Build());
```

### Screenshots
![screen shot 2018-02-21 at 10 19 12 am](https://user-images.githubusercontent.com/5783827/36488142-bd58a260-16f0-11e8-9b22-112a3ed0ba41.png)

**Comment by cjlotz** [comment]
@gabrielrobert Just to clarify, this is happening when running your app via Xamarin Test Cloud service?

**Comment by cjlotz** [comment]
@gabrielrobert seems to be related [to this](https://chrisrisner.com/Xamarin-iOS-Error-Confusion)

**Comment by gabrielrobert** [comment]
@cjlotz Exactly. Have you ever heard of this problem? Is there something we can do in your (very useful!) library?

Just disabling Calabash is not a solution, unfortunately.

**Comment by cjlotz** [comment]
Unfortunately this is outside the scope/control of the messaging library.  The enabling/disabling of Calabash lies in the hands of the app developer, not in hands of a 3rd party library.  From the [Xamarin docs](https://developer.xamarin.com/guides/xamarin-forms/deployment-testing/uitest-and-test-cloud) they mention that you should only set the `ENABLE_TEST_CLOUD` compiler directive for Debug builds and not Release builds as the app will be rejected.  Are you doing this?

**Comment by gabrielrobert** [comment]
This is what I expected, thank you for your time @cjlotz.
