### ISSUE TITLE
Request for the ability to display the name during a call if it's not available(willing to help implement this feature, if someone more experienced can provide guidance).

### ISSUE THREAD

**Issue by johnfredrick** [cjlotz/Xamarin.Plugins#93]
Is it possible to display the name property when making  a call?

**Comment by cjlotz** [comment]
As the plugin makes use of the native dialing api's/interfaces, it is limited to what these api's/interface support.  Only the UWP dialer supports showing the name of the contact and will work as requested, but not any of the other platforms.
