### ISSUE TITLE
Calling phoneDialer.MakePhoneCall for iOS without autodialing

### ISSUE THREAD

**Issue by rubenc57** [cjlotz/Xamarin.Plugins#95]
Hello

Can I call the phoneDialer.MakePhoneCall function for iOS to show the **Phone -> Keypad** instead of the **Cancel - Call window** and let the user decide to call or go to contacts to add the number I'm trying to call? Like in Android

**Phone -> Keypad**
![img_6057_s](https://user-images.githubusercontent.com/20931876/38151645-f496f3e0-3418-11e8-91d6-9cf12eba65ea.png)

**Cancel - Call window**
![img_6060_s](https://user-images.githubusercontent.com/20931876/38151650-f96e276c-3418-11e8-93b2-baa863189d8a.png)

Best Regards
rubenc

**Comment by cjlotz** [comment]
@rubenc57 Unfortunately this does not seem possible via the `NSUrl` and [openurl](https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl) method that the plugin uses for making the phone calls.
