### ISSUE TITLE
Detect an incoming call inside Xamarin Forms

### ISSUE THREAD

**Issue by hashimks** [cjlotz/Xamarin.Plugins#97]
Hello,

Is this plugin detects an incoming call inside an app? Also is it gives an event handler such that when an incoming call happens, the event triggers to do something.

Please help me.

**Comment by cjlotz** [comment]
Unfortunately this falls outside the scope of the plugin.  The plugin makes phone calls, send sms's or emails and does not listen for and respond to any incoming actions.

**Comment by hashimks** [comment]
Thanks @cjlotz 

Do you know any plugins or links which can perform what i have asked for?

**Comment by cjlotz** [comment]
Not, unfortunately not aware of any

**Comment by hashimks** [comment]
Or do you know any plugin for getting the current App state? like whether app is idle or active?
