### ISSUE TITLE
Cannot work on IOS

### ISSUE THREAD

**Issue by TianyiChen-1** [cjlotz/Xamarin.Plugins#98]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information
canOpenURL: failed for URL: "tel:0000000000" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
Version Number of Plugin:
5.20
Device Tested On:
n/a
Simulator Tested On:
iphone simulator ios 11.2

Version of VS: 
vs2017 15.6.5
Version of Xamarin:
2.5.1.444934
Versions of other things you are using:
n/a
### Steps to reproduce the Behavior
  phoneNumber.Clicked += (sender, e) => {
                Console.WriteLine("Pressed");
                var PhoneCallTask = CrossMessaging.Current.PhoneDialer;
                if (PhoneCallTask.CanMakePhoneCall)
                    PhoneCallTask.MakePhoneCall("+862368629315");

            };
Just create any button and add this event handler
### Expected Behavior
I expect the iphone go to the dial number view
### Actual Behavior
No transition happens 
### Screenshots
![20180409214341](https://user-images.githubusercontent.com/26310794/38535078-1f04e7f8-3c3f-11e8-82f1-78a607598694.png)

**Comment by cjlotz** [comment]
Phone calls are not supported on the iOS Simulators.  You need to use a real device.
